name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      rqbit:
        image: ikatson/rqbit:latest
        env:
          RQBIT_HTTP_BASIC_AUTH_USERPASS: admin:adminadmin
          RQBIT_HTTP_API_ALLOW_CREATE: true
        ports:
          - '3030:3030'
          - '4240:4240'
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # https://github.com/wyvox/action-setup-pnpm
      - uses: wyvox/action-setup-pnpm@d84148cd87d55adb709e92120c709b88d15bceac # v4.0.0
        with:
          node-version: 26

      - name: lint
        run: pnpm run lint

      - name: test
        run: pnpm run test
